### ISSUE TITLE
10033725 - Unable to make any changes to this website. 

### ISSUE THREAD

**Issue by aqeelasinglee** [ConsenSysMesh/adhara-ui-boilerplate-elm#6]
INT - http://resinfix-ltd-new.sites3.bonlineapp.com/
EXT - www.resinfix.co.uk

Hi Guys, 
We are unable to make any changes to the Appearance/colours section of the website. 

The website would also randomly change after small changes are made 
_(when adding a line of text in a text box, other changes would occur, like background images and colour changes)_

Thank you.

**Comment by JasoonS** [comment]
@aqeelasinglee I think you have us confused with someone else, we are in no way associated with resinfix
